semantic_models:
  #セマンティックモデルの名前
  - name: products
    description: |
      商品ディメンションテーブル。商品粒度で1商品1行のテーブル。
    #dbtモデルとスキーマの名前
    model: ref('products')
    #エンティティ。通常はテーブルのキーに対応する。
    entities:
      - name: product
        type: primary
        expr: product_id
    #ディメンション。カテゴリカルまたは時間のいずれか。メトリクスに追加のコンテキストを加える。典型的なクエリパターンは「ディメンション別メトリクス」。
    dimensions:
      - name: product_name
        type: categorical
      - name: product_type
        type: categorical
      - name: product_description
        type: categorical
      - name: is_food_item
        type: categorical
      - name: is_drink_item
        type: categorical
      - name: product_price
        type: categorical
